// // --------------------------------------------------------------------------------------------------------------------
// // <copyright file="InitializationVectorGenerationMode.cs" company="Alkami Technology, Inc.">
// //   Copyright 2013 Alkami Technology, Inc.  All rights reserved.
// // </copyright>
// // <summary>
// //
// // </summary>
// // --------------------------------------------------------------------------------------------------------------------
namespace Alkami.TrackableObjects.Plugins.Cryptography
{
    /// <summary>
    /// InitializationVectorGenerationMode
    /// </summary>
    public enum InitializationVectorGenerationMode
    {
        /// <summary>
        /// The none
        /// </summary>
        None=0,
        /// <summary>
        /// The binary
        /// </summary>
        Binary,
        /// <summary>
        /// make sure the generated byte array is valid printable ascii. Less entropy but convenient for transmission. Not recommended.
        /// </summary>
        Ascii,
    }
}