//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alkami.MicroServices.Settings.Data.Validations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alkami.MicroServices.Settings.Data.Validations.ValidationErrors", typeof(ValidationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item was provided which did not have a valid ItemType. Please correct your request and try again..
        /// </summary>
        internal static string ItemInvalidItemType {
            get {
                return ResourceManager.GetString("ItemInvalidItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item was provided which did not have a name. Please correct your request and try again..
        /// </summary>
        internal static string ItemInvalidName {
            get {
                return ResourceManager.GetString("ItemInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item was provided which did not specify a valid Parent Id. Please correct your request and try again..
        /// </summary>
        internal static string ItemInvalidParentId {
            get {
                return ResourceManager.GetString("ItemInvalidParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item setting was provided which did not have a valid name. Please correct your request and try again..
        /// </summary>
        internal static string ItemSettingInvalidName {
            get {
                return ResourceManager.GetString("ItemSettingInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to validate a null entity. Please check your request for invalid entries and try again..
        /// </summary>
        internal static string NoEntityWasPresentToValidate {
            get {
                return ResourceManager.GetString("NoEntityWasPresentToValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A provider was provided which did not have valid assembly information. Please correct your request and try again..
        /// </summary>
        internal static string ProviderAssemblyInfoInvalid {
            get {
                return ResourceManager.GetString("ProviderAssemblyInfoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A provider was provided which did not have a valid name. Please correct your request and try again..
        /// </summary>
        internal static string ProviderInvalidName {
            get {
                return ResourceManager.GetString("ProviderInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A provider setting was provided which did not have a valid name. Please check your request for errors and try again..
        /// </summary>
        internal static string ProviderSettingInvalidName {
            get {
                return ResourceManager.GetString("ProviderSettingInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A provider type was provided which did not have a valid display name. Please correct your request and try again..
        /// </summary>
        internal static string ProviderTypeInvalidDisplayName {
            get {
                return ResourceManager.GetString("ProviderTypeInvalidDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A provider type was provided which did not have a valid name. Please correct your request and try again..
        /// </summary>
        internal static string ProviderTypeInvalidName {
            get {
                return ResourceManager.GetString("ProviderTypeInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ItemType and the ItemTypes filter properties cannot be used together. Both cannot be used for the same request..
        /// </summary>
        internal static string RedundantItemTypeFilterError {
            get {
                return ResourceManager.GetString("RedundantItemTypeFilterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred during validation. Please check your request for errors and try again..
        /// </summary>
        internal static string UnknownValidationError {
            get {
                return ResourceManager.GetString("UnknownValidationError", resourceCulture);
            }
        }
    }
}
